//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.11.20 at 12:19:23 PM CET 
//


package nl.dijkrosoft.cv.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CvType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CvType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="personalia" type="{}PersonaliaType"/>
 *         &lt;element name="regulier-onderwijs" type="{}OpleidingenType"/>
 *         &lt;element name="it-opleidingen" type="{}OpleidingenType"/>
 *         &lt;element name="talen" type="{}ItemType"/>
 *         &lt;element name="ervaringen" type="{}ErvaringenType"/>
 *         &lt;element name="opdrachten" type="{}OpdrachtenType"/>
 *       &lt;/sequence>
 *       &lt;attribute name="persoon" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CvType", propOrder = {
    "personalia",
    "regulierOnderwijs",
    "itOpleidingen",
    "talen",
    "ervaringen",
    "opdrachten"
})
public class CvType {

    @XmlElement(required = true)
    protected PersonaliaType personalia;
    @XmlElement(name = "regulier-onderwijs", required = true)
    protected OpleidingenType regulierOnderwijs;
    @XmlElement(name = "it-opleidingen", required = true)
    protected OpleidingenType itOpleidingen;
    @XmlElement(required = true)
    protected ItemType talen;
    @XmlElement(required = true)
    protected ErvaringenType ervaringen;
    @XmlElement(required = true)
    protected OpdrachtenType opdrachten;
    @XmlAttribute
    protected String persoon;

    /**
     * Gets the value of the personalia property.
     * 
     * @return
     *     possible object is
     *     {@link PersonaliaType }
     *     
     */
    public PersonaliaType getPersonalia() {
        return personalia;
    }

    /**
     * Sets the value of the personalia property.
     * 
     * @param value
     *     allowed object is
     *     {@link PersonaliaType }
     *     
     */
    public void setPersonalia(PersonaliaType value) {
        this.personalia = value;
    }

    /**
     * Gets the value of the regulierOnderwijs property.
     * 
     * @return
     *     possible object is
     *     {@link OpleidingenType }
     *     
     */
    public OpleidingenType getRegulierOnderwijs() {
        return regulierOnderwijs;
    }

    /**
     * Sets the value of the regulierOnderwijs property.
     * 
     * @param value
     *     allowed object is
     *     {@link OpleidingenType }
     *     
     */
    public void setRegulierOnderwijs(OpleidingenType value) {
        this.regulierOnderwijs = value;
    }

    /**
     * Gets the value of the itOpleidingen property.
     * 
     * @return
     *     possible object is
     *     {@link OpleidingenType }
     *     
     */
    public OpleidingenType getItOpleidingen() {
        return itOpleidingen;
    }

    /**
     * Sets the value of the itOpleidingen property.
     * 
     * @param value
     *     allowed object is
     *     {@link OpleidingenType }
     *     
     */
    public void setItOpleidingen(OpleidingenType value) {
        this.itOpleidingen = value;
    }

    /**
     * Gets the value of the talen property.
     * 
     * @return
     *     possible object is
     *     {@link ItemType }
     *     
     */
    public ItemType getTalen() {
        return talen;
    }

    /**
     * Sets the value of the talen property.
     * 
     * @param value
     *     allowed object is
     *     {@link ItemType }
     *     
     */
    public void setTalen(ItemType value) {
        this.talen = value;
    }

    /**
     * Gets the value of the ervaringen property.
     * 
     * @return
     *     possible object is
     *     {@link ErvaringenType }
     *     
     */
    public ErvaringenType getErvaringen() {
        return ervaringen;
    }

    /**
     * Sets the value of the ervaringen property.
     * 
     * @param value
     *     allowed object is
     *     {@link ErvaringenType }
     *     
     */
    public void setErvaringen(ErvaringenType value) {
        this.ervaringen = value;
    }

    /**
     * Gets the value of the opdrachten property.
     * 
     * @return
     *     possible object is
     *     {@link OpdrachtenType }
     *     
     */
    public OpdrachtenType getOpdrachten() {
        return opdrachten;
    }

    /**
     * Sets the value of the opdrachten property.
     * 
     * @param value
     *     allowed object is
     *     {@link OpdrachtenType }
     *     
     */
    public void setOpdrachten(OpdrachtenType value) {
        this.opdrachten = value;
    }

    /**
     * Gets the value of the persoon property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPersoon() {
        return persoon;
    }

    /**
     * Sets the value of the persoon property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPersoon(String value) {
        this.persoon = value;
    }

}
