//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.11.20 at 12:19:23 PM CET 
//


package nl.dijkrosoft.cv.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ErvaringenType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ErvaringenType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="methods" type="{}ItemType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="tools" type="{}ItemType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="talen" type="{}ItemType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="appservers" type="{}ItemType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="technologies" type="{}ItemType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="besturingssystemen" type="{}ItemType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ErvaringenType", propOrder = {
    "methods",
    "tools",
    "talen",
    "appservers",
    "technologies",
    "besturingssystemen"
})
public class ErvaringenType {

    protected List<ItemType> methods;
    protected List<ItemType> tools;
    protected List<ItemType> talen;
    protected List<ItemType> appservers;
    protected List<ItemType> technologies;
    protected List<ItemType> besturingssystemen;

    /**
     * Gets the value of the methods property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the methods property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMethods().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ItemType }
     * 
     * 
     */
    public List<ItemType> getMethods() {
        if (methods == null) {
            methods = new ArrayList<ItemType>();
        }
        return this.methods;
    }

    /**
     * Gets the value of the tools property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the tools property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTools().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ItemType }
     * 
     * 
     */
    public List<ItemType> getTools() {
        if (tools == null) {
            tools = new ArrayList<ItemType>();
        }
        return this.tools;
    }

    /**
     * Gets the value of the talen property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the talen property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTalen().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ItemType }
     * 
     * 
     */
    public List<ItemType> getTalen() {
        if (talen == null) {
            talen = new ArrayList<ItemType>();
        }
        return this.talen;
    }

    /**
     * Gets the value of the appservers property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the appservers property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAppservers().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ItemType }
     * 
     * 
     */
    public List<ItemType> getAppservers() {
        if (appservers == null) {
            appservers = new ArrayList<ItemType>();
        }
        return this.appservers;
    }

    /**
     * Gets the value of the technologies property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the technologies property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTechnologies().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ItemType }
     * 
     * 
     */
    public List<ItemType> getTechnologies() {
        if (technologies == null) {
            technologies = new ArrayList<ItemType>();
        }
        return this.technologies;
    }

    /**
     * Gets the value of the besturingssystemen property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the besturingssystemen property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBesturingssystemen().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ItemType }
     * 
     * 
     */
    public List<ItemType> getBesturingssystemen() {
        if (besturingssystemen == null) {
            besturingssystemen = new ArrayList<ItemType>();
        }
        return this.besturingssystemen;
    }

}
