//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.11.20 at 12:19:23 PM CET 
//


package nl.dijkrosoft.cv.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for KlantType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="KlantType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="bedrijfsnaam" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="branche" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="plaats" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="contactpersonen" type="{}ContactPersonenType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "KlantType", propOrder = {
    "bedrijfsnaam",
    "branche",
    "plaats",
    "contactpersonen"
})
public class KlantType {

    @XmlElement(required = true)
    protected String bedrijfsnaam;
    @XmlElement(required = true)
    protected String branche;
    @XmlElement(required = true)
    protected String plaats;
    @XmlElement(required = true)
    protected ContactPersonenType contactpersonen;

    /**
     * Gets the value of the bedrijfsnaam property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBedrijfsnaam() {
        return bedrijfsnaam;
    }

    /**
     * Sets the value of the bedrijfsnaam property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBedrijfsnaam(String value) {
        this.bedrijfsnaam = value;
    }

    /**
     * Gets the value of the branche property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBranche() {
        return branche;
    }

    /**
     * Sets the value of the branche property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBranche(String value) {
        this.branche = value;
    }

    /**
     * Gets the value of the plaats property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlaats() {
        return plaats;
    }

    /**
     * Sets the value of the plaats property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlaats(String value) {
        this.plaats = value;
    }

    /**
     * Gets the value of the contactpersonen property.
     * 
     * @return
     *     possible object is
     *     {@link ContactPersonenType }
     *     
     */
    public ContactPersonenType getContactpersonen() {
        return contactpersonen;
    }

    /**
     * Sets the value of the contactpersonen property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContactPersonenType }
     *     
     */
    public void setContactpersonen(ContactPersonenType value) {
        this.contactpersonen = value;
    }

}
