//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.11.20 at 12:19:23 PM CET 
//


package nl.dijkrosoft.cv.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for OpdrachtType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OpdrachtType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="periode" type="{}PeriodeType"/>
 *         &lt;element name="klant" type="{}KlantType"/>
 *         &lt;element name="rol" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="werkgebied" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="bijdrage" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="technologie" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OpdrachtType", propOrder = {
    "periode",
    "klant",
    "rol",
    "werkgebied",
    "bijdrage",
    "technologie"
})
public class OpdrachtType {

    @XmlElement(required = true)
    protected PeriodeType periode;
    @XmlElement(required = true)
    protected KlantType klant;
    @XmlElement(required = true)
    protected String rol;
    @XmlElement(required = true)
    protected String werkgebied;
    @XmlElement(required = true)
    protected String bijdrage;
    @XmlElement(required = true)
    protected String technologie;

    /**
     * Gets the value of the periode property.
     * 
     * @return
     *     possible object is
     *     {@link PeriodeType }
     *     
     */
    public PeriodeType getPeriode() {
        return periode;
    }

    /**
     * Sets the value of the periode property.
     * 
     * @param value
     *     allowed object is
     *     {@link PeriodeType }
     *     
     */
    public void setPeriode(PeriodeType value) {
        this.periode = value;
    }

    /**
     * Gets the value of the klant property.
     * 
     * @return
     *     possible object is
     *     {@link KlantType }
     *     
     */
    public KlantType getKlant() {
        return klant;
    }

    /**
     * Sets the value of the klant property.
     * 
     * @param value
     *     allowed object is
     *     {@link KlantType }
     *     
     */
    public void setKlant(KlantType value) {
        this.klant = value;
    }

    /**
     * Gets the value of the rol property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRol() {
        return rol;
    }

    /**
     * Sets the value of the rol property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRol(String value) {
        this.rol = value;
    }

    /**
     * Gets the value of the werkgebied property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWerkgebied() {
        return werkgebied;
    }

    /**
     * Sets the value of the werkgebied property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWerkgebied(String value) {
        this.werkgebied = value;
    }

    /**
     * Gets the value of the bijdrage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBijdrage() {
        return bijdrage;
    }

    /**
     * Sets the value of the bijdrage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBijdrage(String value) {
        this.bijdrage = value;
    }

    /**
     * Gets the value of the technologie property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTechnologie() {
        return technologie;
    }

    /**
     * Sets the value of the technologie property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTechnologie(String value) {
        this.technologie = value;
    }

}
