//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.11.20 at 12:19:23 PM CET 
//


package nl.dijkrosoft.cv.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for OpleidingType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OpleidingType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="school" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="cursus" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="periode" type="{}PeriodeType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OpleidingType", propOrder = {
    "school",
    "cursus",
    "periode"
})
public class OpleidingType {

    @XmlElement(required = true)
    protected String school;
    @XmlElement(required = true)
    protected String cursus;
    @XmlElement(required = true)
    protected PeriodeType periode;

    /**
     * Gets the value of the school property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSchool() {
        return school;
    }

    /**
     * Sets the value of the school property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSchool(String value) {
        this.school = value;
    }

    /**
     * Gets the value of the cursus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCursus() {
        return cursus;
    }

    /**
     * Sets the value of the cursus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCursus(String value) {
        this.cursus = value;
    }

    /**
     * Gets the value of the periode property.
     * 
     * @return
     *     possible object is
     *     {@link PeriodeType }
     *     
     */
    public PeriodeType getPeriode() {
        return periode;
    }

    /**
     * Sets the value of the periode property.
     * 
     * @param value
     *     allowed object is
     *     {@link PeriodeType }
     *     
     */
    public void setPeriode(PeriodeType value) {
        this.periode = value;
    }

}
